# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import image_retrival_pb2 as image__retrival__pb2


class SimilarImageStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.FindSimilar = channel.unary_unary(
        '/SimilarImage/FindSimilar',
        request_serializer=image__retrival__pb2.ImageFileIn.SerializeToString,
        response_deserializer=image__retrival__pb2.ImageFileOut.FromString,
        )


class SimilarImageServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def FindSimilar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimilarImageServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'FindSimilar': grpc.unary_unary_rpc_method_handler(
          servicer.FindSimilar,
          request_deserializer=image__retrival__pb2.ImageFileIn.FromString,
          response_serializer=image__retrival__pb2.ImageFileOut.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SimilarImage', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
