# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import edgedetect_pb2 as edgedetect__pb2


class EdgedetectStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectEdge = channel.unary_unary(
        '/Edgedetect/DetectEdge',
        request_serializer=edgedetect__pb2.ImageFile.SerializeToString,
        response_deserializer=edgedetect__pb2.ImageFile.FromString,
        )


class EdgedetectServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectEdge(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EdgedetectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectEdge': grpc.unary_unary_rpc_method_handler(
          servicer.DetectEdge,
          request_deserializer=edgedetect__pb2.ImageFile.FromString,
          response_serializer=edgedetect__pb2.ImageFile.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Edgedetect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
