# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edgedetect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='edgedetect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x65\x64gedetect.proto\".\n\tImageFile\x12\r\n\x05image\x18\x01 \x01(\t\x12\x12\n\nimage_type\x18\x02 \x01(\t24\n\nEdgedetect\x12&\n\nDetectEdge\x12\n.ImageFile\x1a\n.ImageFile\"\x00\x62\x06proto3')
)




_IMAGEFILE = _descriptor.Descriptor(
  name='ImageFile',
  full_name='ImageFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ImageFile.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_type', full_name='ImageFile.image_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['ImageFile'] = _IMAGEFILE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageFile = _reflection.GeneratedProtocolMessageType('ImageFile', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEFILE,
  __module__ = 'edgedetect_pb2'
  # @@protoc_insertion_point(class_scope:ImageFile)
  ))
_sym_db.RegisterMessage(ImageFile)



_EDGEDETECT = _descriptor.ServiceDescriptor(
  name='Edgedetect',
  full_name='Edgedetect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=68,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectEdge',
    full_name='Edgedetect.DetectEdge',
    index=0,
    containing_service=None,
    input_type=_IMAGEFILE,
    output_type=_IMAGEFILE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDGEDETECT)

DESCRIPTOR.services_by_name['Edgedetect'] = _EDGEDETECT

# @@protoc_insertion_point(module_scope)
