# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_detect.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import face_common_pb2 as face__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_detect.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x66\x61\x63\x65_detect.proto\x1a\x11\x66\x61\x63\x65_common.proto26\n\nFaceDetect\x12(\n\x08\x46indFace\x12\t.ImageRGB\x1a\x0f.FaceDetections\"\x00\x62\x06proto3')
  ,
  dependencies=[face__common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FACEDETECT = _descriptor.ServiceDescriptor(
  name='FaceDetect',
  full_name='FaceDetect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=40,
  serialized_end=94,
  methods=[
  _descriptor.MethodDescriptor(
    name='FindFace',
    full_name='FaceDetect.FindFace',
    index=0,
    containing_service=None,
    input_type=face__common__pb2._IMAGERGB,
    output_type=face__common__pb2._FACEDETECTIONS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEDETECT)

DESCRIPTOR.services_by_name['FaceDetect'] = _FACEDETECT

# @@protoc_insertion_point(module_scope)
