# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import network_analytics_robustness_pb2 as network__analytics__robustness__pb2


class NetworkAnalyticsRobustnessStub(object):
  """/// End MostImportantNodesEdgesSubset

  /// Network Analytics Robustness Services

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MinNodesToRemove = channel.unary_unary(
        '/NetworkAnalyticsRobustness/MinNodesToRemove',
        request_serializer=network__analytics__robustness__pb2.MinNodesToRemoveRequest.SerializeToString,
        response_deserializer=network__analytics__robustness__pb2.MinNodesToRemoveResponse.FromString,
        )
    self.MostImportantNodesEdgesSubset = channel.unary_unary(
        '/NetworkAnalyticsRobustness/MostImportantNodesEdgesSubset',
        request_serializer=network__analytics__robustness__pb2.MostImportantNodesEdgesSubsetRequest.SerializeToString,
        response_deserializer=network__analytics__robustness__pb2.MostImportantNodesEdgesSubsetResponse.FromString,
        )


class NetworkAnalyticsRobustnessServicer(object):
  """/// End MostImportantNodesEdgesSubset

  /// Network Analytics Robustness Services

  """

  def MinNodesToRemove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MostImportantNodesEdgesSubset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetworkAnalyticsRobustnessServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MinNodesToRemove': grpc.unary_unary_rpc_method_handler(
          servicer.MinNodesToRemove,
          request_deserializer=network__analytics__robustness__pb2.MinNodesToRemoveRequest.FromString,
          response_serializer=network__analytics__robustness__pb2.MinNodesToRemoveResponse.SerializeToString,
      ),
      'MostImportantNodesEdgesSubset': grpc.unary_unary_rpc_method_handler(
          servicer.MostImportantNodesEdgesSubset,
          request_deserializer=network__analytics__robustness__pb2.MostImportantNodesEdgesSubsetRequest.FromString,
          response_serializer=network__analytics__robustness__pb2.MostImportantNodesEdgesSubsetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NetworkAnalyticsRobustness', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
