# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face_common.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x66\x61\x63\x65_common.proto\"\x1b\n\x08ImageRGB\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"9\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"1\n\x0e\x46\x61\x63\x65\x44\x65tections\x12\x1f\n\tface_bbox\x18\x01 \x03(\x0b\x32\x0c.BoundingBox\"@\n\rFaceLandmarks\x12\x16\n\x0elandmark_model\x18\x01 \x01(\t\x12\x17\n\x05point\x18\x02 \x03(\x0b\x32\x08.Point2D\"p\n\x18\x46\x61\x63\x65LandmarkDescriptions\x12\x16\n\x0elandmark_model\x18\x01 \x01(\t\x12\x1c\n\x14landmark_description\x18\x02 \x03(\t\x12\x1e\n\x0clandmark_avg\x18\x03 \x03(\x0b\x32\x08.Point2D\">\n\x12\x46\x61\x63\x65LandmarkModels\x12(\n\x05model\x18\x01 \x03(\x0b\x32\x19.FaceLandmarkDescriptionsb\x06proto3')
)




_IMAGERGB = _descriptor.Descriptor(
  name='ImageRGB',
  full_name='ImageRGB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='ImageRGB.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=48,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='BoundingBox.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='BoundingBox.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='BoundingBox.w', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='BoundingBox.h', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=107,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point2D.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point2D.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=140,
)


_FACEDETECTIONS = _descriptor.Descriptor(
  name='FaceDetections',
  full_name='FaceDetections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_bbox', full_name='FaceDetections.face_bbox', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=191,
)


_FACELANDMARKS = _descriptor.Descriptor(
  name='FaceLandmarks',
  full_name='FaceLandmarks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmark_model', full_name='FaceLandmarks.landmark_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='FaceLandmarks.point', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=257,
)


_FACELANDMARKDESCRIPTIONS = _descriptor.Descriptor(
  name='FaceLandmarkDescriptions',
  full_name='FaceLandmarkDescriptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmark_model', full_name='FaceLandmarkDescriptions.landmark_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark_description', full_name='FaceLandmarkDescriptions.landmark_description', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark_avg', full_name='FaceLandmarkDescriptions.landmark_avg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=371,
)


_FACELANDMARKMODELS = _descriptor.Descriptor(
  name='FaceLandmarkModels',
  full_name='FaceLandmarkModels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='FaceLandmarkModels.model', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=435,
)

_FACEDETECTIONS.fields_by_name['face_bbox'].message_type = _BOUNDINGBOX
_FACELANDMARKS.fields_by_name['point'].message_type = _POINT2D
_FACELANDMARKDESCRIPTIONS.fields_by_name['landmark_avg'].message_type = _POINT2D
_FACELANDMARKMODELS.fields_by_name['model'].message_type = _FACELANDMARKDESCRIPTIONS
DESCRIPTOR.message_types_by_name['ImageRGB'] = _IMAGERGB
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.message_types_by_name['FaceDetections'] = _FACEDETECTIONS
DESCRIPTOR.message_types_by_name['FaceLandmarks'] = _FACELANDMARKS
DESCRIPTOR.message_types_by_name['FaceLandmarkDescriptions'] = _FACELANDMARKDESCRIPTIONS
DESCRIPTOR.message_types_by_name['FaceLandmarkModels'] = _FACELANDMARKMODELS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRGB = _reflection.GeneratedProtocolMessageType('ImageRGB', (_message.Message,), dict(
  DESCRIPTOR = _IMAGERGB,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:ImageRGB)
  ))
_sym_db.RegisterMessage(ImageRGB)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), dict(
  DESCRIPTOR = _POINT2D,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:Point2D)
  ))
_sym_db.RegisterMessage(Point2D)

FaceDetections = _reflection.GeneratedProtocolMessageType('FaceDetections', (_message.Message,), dict(
  DESCRIPTOR = _FACEDETECTIONS,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetections)
  ))
_sym_db.RegisterMessage(FaceDetections)

FaceLandmarks = _reflection.GeneratedProtocolMessageType('FaceLandmarks', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKS,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarks)
  ))
_sym_db.RegisterMessage(FaceLandmarks)

FaceLandmarkDescriptions = _reflection.GeneratedProtocolMessageType('FaceLandmarkDescriptions', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKDESCRIPTIONS,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarkDescriptions)
  ))
_sym_db.RegisterMessage(FaceLandmarkDescriptions)

FaceLandmarkModels = _reflection.GeneratedProtocolMessageType('FaceLandmarkModels', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKMODELS,
  __module__ = 'face_common_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarkModels)
  ))
_sym_db.RegisterMessage(FaceLandmarkModels)


# @@protoc_insertion_point(module_scope)
