# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import translate_pb2 as translate__pb2


class TranslationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.translate = channel.unary_unary(
        '/Translation/translate',
        request_serializer=translate__pb2.Request.SerializeToString,
        response_deserializer=translate__pb2.Result.FromString,
        )


class TranslationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def translate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TranslationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'translate': grpc.unary_unary_rpc_method_handler(
          servicer.translate,
          request_deserializer=translate__pb2.Request.FromString,
          response_serializer=translate__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Translation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
